<?xml version="1.0" encoding="UTF-8"?>

<!-- 아래 DTD 내용을 토대로 XML문서를 완성한다.
	 데이터는 자신이 좋아하는 가수의 곡 정보를 3곡 이상 등록한다. -->

<!DOCTYPE compactDiscs
[
<!ELEMENT compactDiscs (compactDisc+)>
<!ELEMENT compactDisc (artist, title, tracks, price)>
<!ELEMENT artist (#PCDATA)>
<!ATTLIST artist type (individual | band) #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title numberOfTracks CDATA #REQUIRED>
<!ELEMENT tracks (track+)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT track (#PCDATA)>
]>
<compactDiscs>
	<compactDisc>
		<artist type="individual">아리아나 그란데</artist>
		<title numberOfTracks="1">thank u, next</title>
		<tracks>
			<track>7 rings</track>
			<track>imagine</track>
			<track>thank u, next</track>
		</tracks>
		<price>15000</price>
	</compactDisc>
	<compactDisc>
		<artist type="individual">아리아나 그란데</artist>
		<title numberOfTracks="2">Dangerous Woman</title>
		<tracks>
			<track>Greedy</track>
			<track>Side to Side</track>
			<track>Into You</track>
		</tracks>
		<price>15000</price>
	</compactDisc>
	<compactDisc>
		<artist type="individual">아리아나 그란데</artist>
		<title numberOfTracks="3">Sweetner</title>
		<tracks>
			<track>God is woman</track>
			<track>Breathin</track>
			<track>no tears to cry</track>
		</tracks>
		<price>15000</price>
	</compactDisc>
</compactDiscs>