<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!-- 문서의 루트엘리먼트가 memberList다. 부터 시작
	 +는 해당 엘리먼트가 다수개 있다
	 ?는 해당 엘리먼트가 있기도 하고 없기도 하다
	 name에는 피시데이터가 있다.
	 ATTLIST는 속성 리스트 : mid는 각 멤버인포를 구분하는 역할을 하는 속성이다. -->
<!DOCTYPE memberList
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, telephone, curriculum?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculum (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>

<memberList>
	<!-- 루트 엘리먼트는 하나
		 루트 엘리먼트 이름은 『~~~~.xml』 파일 이름과 동일한 이름 사용
		 개인 정보를 표현할 수 있는 문서
		 복수의 데이터를 표현하는 경우 중간에 적절한 부모 태그 지정
		 동일한 이름을 가진 엘리먼트인 경우 적절한 속성과 값 부여
		 엘리먼트 하위에는 엘리먼트 또는 데이터만 구성할 수 있도록 처리
		 특수문자가 포함된 데이터인 경우 CDATA 섹션으로 처리  -->
		 <memberInfo mid="1">
		 	<name>윤유동</name>
		 	<telephone><![CDATA[010-2944-6341]]></telephone>
		 	<curriculum>
		 		<sub>JAVA SE</sub>
		 		<sub>ORACEL</sub>
		 		<sub><![CDATA[Servlet&JSP]]></sub>
		 	</curriculum>
		 </memberInfo>
		 <memberInfo mid="2">
		 	<name>박효빈</name>
		 	<telephone><![CDATA[CDATA010-5541-7266]]></telephone>
		 </memberInfo>
</memberList>